import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

const exportPDF = (products = [], summary = {}, user = { name: "Admin" }) => {
  const doc = new jsPDF();
  const currentDate = new Date().toLocaleDateString();
  const currentTime = new Date().toLocaleTimeString();

  // 1. Header & Title Section
  doc.setFontSize(20);
  doc.setTextColor(33, 150, 243);
  doc.text("INVENTORY MANAGEMENT REPORT", 14, 20);

  doc.setFontSize(10);
  doc.setTextColor(100);
  doc.text(`Generated Date: ${currentDate} ${currentTime}`, 14, 26);
  doc.line(14, 29, 196, 29); // Divider line

  // 2. Executive Summary Block
  doc.setFontSize(12);
  doc.setTextColor(0);
  doc.text("Executive Summary", 14, 37);

  autoTable(doc, {
    startY: 40,
    head: [["Metric", "Value"]],
    body: [
      ["Total Products", String(summary.visibleProducts || products.length)],
      ["Low Stock Items", String(summary.lowStock || 0)],
      ["Categories Included", String(summary.categoriesCount || 0)],
      ["Total Inventory Value", `$${(summary.inventoryValue || 0).toLocaleString()}`],
    ],
    theme: "striped",
    headStyles: { fillColor: [41, 128, 185] },
    margin: { bottom: 10 },
  });

  // 3. Products Data Table
  const tableStartY = doc.lastAutoTable.finalY + 12;
  doc.setFontSize(12);
  doc.text("Product Details", 14, tableStartY - 4);

  autoTable(doc, {
    startY: tableStartY,
    head: [["Name", "Category", "Price", "Qty", "Min", "Status"]],
    body: products.map((item) => [
      item.name || "",
      typeof item.category === "object" ? item.category?.name : item.category || "Uncategorized",
      `$${item.sellingPrice ?? item.price ?? 0}`,
      item.quantity ?? 0,
      item.minStock ?? 0,
      item.quantity <= item.minStock ? "Low Stock" : "In Stock",
    ]),
    theme: "grid",
    headStyles: { fillColor: [52, 73, 94] },
    didDrawPage: (data) => {
      // 4. Footer Section (Runs on every page)
      const pageCount = doc.internal.getNumberOfPages();
      const pageHeight = doc.internal.pageSize.height || doc.internal.pageSize.getHeight();

      doc.setFontSize(9);
      doc.setTextColor(150);

      // Left Footer: Generated By & Timestamp
      doc.text(
        `Generated By: ${user?.name || "System Admin"} | ${currentDate}`,
        14,
        pageHeight - 10
      );

      // Right Footer: Dynamic Page Numbering (Page X of Y)
      doc.text(
        `Page ${data.pageNumber} of ${pageCount}`,
        180,
        pageHeight - 10
      );
    },
  });

  doc.save(`Inventory_Report_${new Date().toISOString().slice(0, 10)}.pdf`);
};

export default exportPDF;